import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
const fast = process.argv.includes('--fast');

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: prod ? "info" : (fast ? "error" : "warning"),
	sourcemap: prod ? false : (fast ? false : true),
	treeShaking: prod ? true : (fast ? false : true),
	minify: prod,
	outfile: 'main.js',
	// 开发模式优化
	...(prod ? {} : {
		incremental: true,
		metafile: false,
		write: true,
		splitting: false,
		// 快速模式额外优化
		...(fast ? {
			keepNames: false,
			legalComments: 'none',
			ignoreAnnotations: true
		} : {})
	})
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}